version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: tododb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: node-app
    ports:
      - "3000:3000"
    environment:
      - MONGO_USER=root
      - MONGO_PASS=example
      - MONGO_DB=tododb
      - MONGO_HOST=mongo
      - PORT=3000
    depends_on:
      - mongo
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
